name: Release

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  release:
    name: Build, Release & Publish
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm ci

      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,build
          projects: ports,adapters

      - name: Build, Release on GitHub & Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run affected:release